version: '3'

services:
  predix-edge-redis:
    image: "predixedge/predix-edge-redis-amd64:1.0.10"
    stdin_open: true
    ports:
      - "6379:6379"
    tty: true
    healthcheck:
      timeout: 5s
      test: exit 0
      retries: 3
      interval: 5s
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - predix-edge-broker_net
networks:
  predix-edge-broker_net:
    external: true
